require("user.colorscheme")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.trouble")
require("user.lualine")
require("user.floaterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.gotobuffer")
require("user.whichkey")
require("user.vim-fugitive")
require("user.autocommands")
require("user.neotest")
require("user.vimwiki")
require("user.dap")
require("user.persistence")
require("user.alpha")
require("user.rest")
require("user.diffview")
require("user.bufferline")
require("user.navic")

-- require("user.mergetool")
-- require("user.buftabline") -- Deprecated
-- require("user.nvim-test")
-- require("user.symbols-outline")
-- require("user.gonvim")
-- require("user.possession")
-- require("user.copilot")
-- require("user.startify")
-- require("user.dashboard")
-- require("user.neorg")
-- require("user.ultest")
-- require("user.toggleterm")
